"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['worktracker.py']
DATA_FILES = []
PKGS = ["gspread"]
OPTIONS = {
    'argv_emulation': False,
    'packages': PKGS
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
