"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

OPTIONS = {
    'argv_emulation': False,
}

setup(
    name='worktracker',
    description='Track your everyday tasks',
    author='Tobias Wennergren',
    author_email='wennergr@gmail.com',
    license='MIT',
    url='https://github.com/wennergr/worktracker',
    app=['worktracker.py'],
    data_files=["worktracker_installer.py"],
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    install_requires=['gspread', "ElementC14N"]
)
